### ISSUE TITLE
Error: An error occured while starting Youtube together !

### ISSUE THREAD

**Issue by ahmadshkour0** [RemyK888/discord-together#3]
Error: An error occured while starting Youtube together !
   at DiscordTogether.createTogetherCode (/home/runner/sssAFASssX4UV4ssssSFASFAssss/node_modules/discord-together/src/DiscordTogether.js:98:31)
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
        
    NOTE : old version is running with me
    
![Screenshot 2021-05-09 215326](https://user-images.githubusercontent.com/73717039/117585141-0e745f00-b111-11eb-9d4a-20803d79ee37.jpg)

**Comment by ahmadshkour0** [comment]
run with me in **index.js**
not in moudle export 🤔
not problem in package 
problem with me :)

**Comment by adamdev-id** [comment]
You can put it on Module Export, it works for me
